import org.gradle.testing.jacoco.tasks.JacocoReport
import org.gradle.internal.os.OperatingSystem
import org.gradle.api.tasks.bundling.Zip
import java.io.File

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.10.2/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    application
    jacoco
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    // Define the main class for the application.
    mainClass = "tetris.App"
}

tasks.named<Test>("test") {
    useJUnitPlatform()
    finalizedBy("jacocoTestReport")
}

tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8"
}

tasks.named<JacocoReport>("jacocoTestReport") {
    dependsOn(tasks.named("test"))
    reports {
        xml.required.set(true)
        html.required.set(true)
    }
    classDirectories.setFrom(
        files(
            classDirectories.files.map {
                fileTree(it) {
                    // Exclude generated App entry and large UI/controller packages
                    exclude("tetris/App.class")
                    exclude("tetris/view/**")
                    exclude("tetris/view/**/**")
                    exclude("tetris/controller/**")
                    exclude("tetris/controller/**/**")
                }
            }
        )
    )
    sourceDirectories.setFrom(files("src/main/java"))
    executionData.setFrom(fileTree(layout.buildDirectory.dir("jacoco")) {
        include("test.exec")
    })
}

// --- Distribution helpers ----------------------------------------------------

private fun ensureWindowsPackaging(): Boolean = OperatingSystem.current().isWindows
private fun ensureMacPackaging(): Boolean = OperatingSystem.current().isMacOsX

val packageName = "Team6Tetris"
val iconFile = rootProject.layout.projectDirectory.file("assets/tetris.ico")
val macIconFile = rootProject.layout.projectDirectory.file("assets/tetris.icns")

tasks.register<Exec>("packageWinAppImage") {
    group = "distribution"
    description = "Create a Windows app-image (contains Team6Tetris.exe) with the bundled icon via jpackage."
    dependsOn(tasks.named("installDist"))
    onlyIf { ensureWindowsPackaging() }

    doFirst {
        val javaHome = System.getenv("JAVA_HOME") ?: System.getProperty("java.home")
        require(!javaHome.isNullOrBlank()) {
            "JAVA_HOME must be set (or java.home available) to locate jpackage."
        }
        val jpackageExecutableName = if (OperatingSystem.current().isWindows) "jpackage.exe" else "jpackage"
        val jpackageExecutable = File(javaHome, "bin/$jpackageExecutableName")
        require(jpackageExecutable.exists()) {
            "Could not find jpackage at ${jpackageExecutable.absolutePath}. Verify JAVA_HOME points to JDK 14+."
        }
        require(iconFile.asFile.exists()) {
            "Icon file not found at ${iconFile.asFile.absolutePath}"
        }

        val appName = application.applicationName
        val inputLibDir = layout.buildDirectory.dir("install/$appName/lib").get().asFile
        require(inputLibDir.exists()) {
            "Distribution libs directory not found at ${inputLibDir.absolutePath}. Run installDist first."
        }

        val destinationDir = layout.buildDirectory.dir("package/windows").get().asFile
        destinationDir.mkdirs()

        val mainJar = "${project.name}.jar"

        commandLine(
            jpackageExecutable.absolutePath,
            "--type", "app-image",
            "--name", packageName,
            "--input", inputLibDir.absolutePath,
            "--dest", destinationDir.absolutePath,
            "--main-class", application.mainClass.get(),
            "--main-jar", mainJar,
            "--icon", iconFile.asFile.absolutePath
        )
    }
}

tasks.register<Zip>("packageWinZip") {
    group = "distribution"
    description = "Zip the Windows app-image for easy distribution."
    dependsOn(tasks.named("packageWinAppImage"))
    onlyIf { ensureWindowsPackaging() }

    val appImageDir = layout.buildDirectory.dir("package/windows/$packageName")
    val outputDir = layout.buildDirectory.dir("package/windows")

    from(appImageDir)
    archiveFileName.set("$packageName-windows.zip")
    destinationDirectory.set(outputDir)
}

tasks.register<Exec>("packageMacAppImage") {
    group = "distribution"
    description = "Create a macOS .app bundle with icon via jpackage."
    dependsOn(tasks.named("installDist"))
    onlyIf { ensureMacPackaging() }

    doFirst {
        val javaHome = System.getenv("JAVA_HOME") ?: System.getProperty("java.home")
        require(!javaHome.isNullOrBlank()) {
            "JAVA_HOME must be set (or java.home available) to locate jpackage."
        }
        val jpackageExecutable = File(javaHome, "bin/jpackage")
        require(jpackageExecutable.exists()) {
            "Could not find jpackage at ${jpackageExecutable.absolutePath}. Verify JAVA_HOME points to JDK 14+."
        }
        require(macIconFile.asFile.exists()) {
            "Icon file (.icns) not found at ${macIconFile.asFile.absolutePath}"
        }

        val appName = application.applicationName
        val inputLibDir = layout.buildDirectory.dir("install/$appName/lib").get().asFile
        require(inputLibDir.exists()) {
            "Distribution libs directory not found at ${inputLibDir.absolutePath}. Run installDist first."
        }

        val destinationDir = layout.buildDirectory.dir("package/macos").get().asFile
        destinationDir.mkdirs()

        val mainJar = "${project.name}.jar"

        commandLine(
            jpackageExecutable.absolutePath,
            "--type", "app-image",
            "--name", packageName,
            "--input", inputLibDir.absolutePath,
            "--dest", destinationDir.absolutePath,
            "--main-class", application.mainClass.get(),
            "--main-jar", mainJar,
            "--icon", macIconFile.asFile.absolutePath
        )
    }
}

tasks.register<Exec>("packageMacDmg") {
    group = "distribution"
    description = "Create a macOS DMG containing the generated .app bundle."
    dependsOn(tasks.named("packageMacAppImage"))
    onlyIf { ensureMacPackaging() }

    doFirst {
        val javaHome = System.getenv("JAVA_HOME") ?: System.getProperty("java.home")
        require(!javaHome.isNullOrBlank()) {
            "JAVA_HOME must be set (or java.home available) to locate jpackage."
        }
        val jpackageExecutable = File(javaHome, "bin/jpackage")
        require(jpackageExecutable.exists()) {
            "Could not find jpackage at ${jpackageExecutable.absolutePath}. Verify JAVA_HOME points to JDK 14+."
        }

        val destinationDir = layout.buildDirectory.dir("package/macos").get().asFile
        val appImage = File(destinationDir, "$packageName.app")
        require(appImage.exists()) {
            "App image not found at ${appImage.absolutePath}. Run packageMacAppImage first."
        }

        commandLine(
            jpackageExecutable.absolutePath,
            "--type", "dmg",
            "--name", packageName,
            "--app-image", appImage.absolutePath,
            "--dest", destinationDir.absolutePath
        )
    }
}
